name: Update terminal screenshots

run-name: Update terminal screenshots

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/main.zig'

jobs:
  build-and-update-screenshot:
    name: Build latest main, download termshot and take screenshot
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - run: zig build
      - name: 'Download termshot and create image'
        run: |
          wget https://github.com/homeport/termshot/releases/download/v0.6.1/termshot_0.6.1_linux_amd64.tar.gz # ubuntu-latest is always x64: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
          tar -xzf term*
          cp zig-out/bin/snestils .
          ./snestils
          ./termshot -c ./snestils
      - name: 'Commit snestils.png to repo'
        run: |
          mv out.png snestils.png
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add snestils.png
          git commit -m "[action] update snestils.png"
          git push
          
